name: Fetch and Update Trial Lessons Data

on:
  workflow_dispatch:

jobs:
  fetch-trial-lessons:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run fetch_trial_lessons script
      run: python fetch_trial_lessons.py
      env:
        ALPHA_CRM_EMAIL: ${{ secrets.ALPHA_CRM_EMAIL }}
        ALPHA_CRM_API_KEY: ${{ secrets.ALPHA_CRM_API_KEY }}
        ALPHA_CRM_HOSTNAME: ${{ secrets.ALPHA_CRM_HOSTNAME }}

    - name: Ensure CSV file exists and is not empty
      run: |
        if [ -z "$(ls -A | grep trial_lessons_)" ]; then
          echo "CSV file is empty or does not exist"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add trial_lessons_*.csv
        git commit -m 'Updated trial lessons data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
