name: Fetch and Update Data

on:
  workflow_dispatch:

jobs:
  fetch-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run fetch_leads script
      run: python fetch_leads.py
      env:
        ALPHA_CRM_EMAIL: ${{ secrets.ALPHA_CRM_EMAIL }}
        ALPHA_CRM_API_KEY: ${{ secrets.ALPHA_CRM_API_KEY }}
        ALPHA_CRM_HOSTNAME: ${{ secrets.ALPHA_CRM_HOSTNAME }}

    - name: Ensure CSV file exists
      run: |
        if [ ! -f leads_on_stage_4.csv ]; then
          echo "leads_on_stage_4.csv file not found!"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add leads_on_stage_4.csv
        git commit -m 'Updated leads data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
