name: Fetch and Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '08 30 * * *'  # 10:30 по времени Словении (GMT+2), что соответствует 08:30 по UTC

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Print debug info
      run: |
        echo "Current time: $(date)"
        echo "Current timezone: $(date +'%Z %z')"

    - name: Run fetch_trial_lessons script
      run: python fetch_trial_lessons.py
      env:
        ALPHA_CRM_EMAIL: ${{ secrets.ALPHA_CRM_EMAIL }}
        ALPHA_CRM_API_KEY: ${{ secrets.ALPHA_CRM_API_KEY }}
        ALPHA_CRM_HOSTNAME: ${{ secrets.ALPHA_CRM_HOSTNAME }}

    - name: Ensure trial lessons CSV file exists and is not empty
      run: |
        if [ ! -s trial_lessons.csv ]; then
          echo "trial_lessons.csv is empty"
          exit 1
        fi

    - name: Run fetch_history_changes script
      run: python fetch_history_changes.py
      env:
        ALPHA_CRM_EMAIL: ${{ secrets.ALPHA_CRM_EMAIL }}
        ALPHA_CRM_API_KEY: ${{ secrets.ALPHA_CRM_API_KEY }}
        ALPHA_CRM_HOSTNAME: ${{ secrets.ALPHA_CRM_HOSTNAME }}

    - name: Ensure leads history changes CSV file exists and is not empty
      run: |
        if [ ! -s leads_history_changes.csv ]; then
          echo "leads_history_changes.csv is empty"
          exit 1
        fi

    - name: Run fetch_customers_with_status_and_source script
      run: python fetch_customers_with_status_and_source.py
      env:
        ALPHA_CRM_EMAIL: ${{ secrets.ALPHA_CRM_EMAIL }}
        ALPHA_CRM_API_KEY: ${{ secrets.ALPHA_CRM_API_KEY }}
        ALPHA_CRM_HOSTNAME: ${{ secrets.ALPHA_CRM_HOSTNAME }}

    - name: Ensure customers statuses and sources CSV file exists and is not empty
      run: |
        if [ ! -s customers_statuses_sources.csv ]; then
          echo "customers_statuses_sources.csv is empty"
          exit 1
        fi

    - name: Run fetch_leads_with_status_and_source script
      run: python fetch_leads_with_status_and_source.py
      env:
        ALPHA_CRM_EMAIL: ${{ secrets.ALPHA_CRM_EMAIL }}
        ALPHA_CRM_API_KEY: ${{ secrets.ALPHA_CRM_API_KEY }}
        ALPHA_CRM_HOSTNAME: ${{ secrets.ALPHA_CRM_HOSTNAME }}

    - name: Ensure leads statuses and sources CSV file exists and is not empty
      run: |
        if [ ! -s leads_statuses_sources.csv ]; then
          echo "leads_statuses_sources.csv is empty"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add trial_lessons.csv leads_history_changes.csv customers_statuses_sources.csv leads_statuses_sources.csv
        git commit -m 'Updated lessons and leads data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
